#!/bin/bash
#
# aqd	control an aqd broker
#
# chkconfig: 35 99 01
# description: runs an aqd broker

# Source function library.
. /etc/init.d/functions

RETVAL=0
prog="aqd"
pidfile="/var/quattor/run/aqd.pid"
twistd="/ms/dist/aquilon/PROJ/aqd/1.1/bin/twistd"

start() {
        echo -n $"Starting $prog: "
	su cdb -c "/ms/dist/aurora/bin/krun -- $twistd --pidfile=$pidfile --logfile=/var/quattor/logs/aqd.log aqd" >/var/tmp/aqd.out 2>&1
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
            touch /var/lock/subsys/$prog
	    success $"$prog startup"
	else
	    failure $"$prog startup"
	fi
        echo
	return $RETVAL
}

stop() {
        echo -n $"Shutting down $prog: "
	RETVAL=0
	if [ -f $pidfile ]; then
		pid=
		read line < $pidfile
		for p in $line ; do
			if [ -z "${p//[0-9]/}" -a -d "/proc/$p" ]; then
				pid="$p"
			fi
		done
		if [ -n "${pid:-}" ]; then
			if checkpid $pid 2>&1; then
				kill -TERM $pid > /dev/null 2>&1
				usleep 100000
				if checkpid $pid && sleep 1 && 
				   checkpid $pid && sleep 3 &&
				   checkpid $pid ; then
					kill -KILL $pid >/dev/null 2>&1
					usleep 100000
				fi
			fi
			checkpid $pid
			RETVAL=$?
		fi
		rm -f $pidfile
	fi

	[ "$RETVAL" -eq 0 ] && success $"$prog shutdown" || success $"$prog shutdown"
        echo
	rm -f /var/lock/subsys/$prog
	return $RETVAL
}

aqstatus() {
	if [ -f $pidfile ]; then
		read pid < $pidfile
		if [ -n "$pid" ]; then
			if checkpid $pid 2>&1; then
				echo $"${prog} is running"
				return 0
			else
				echo $"${prog} is dead but pid file exists"
				return 1
			fi
		fi
	fi
	if [ -f /var/lock/subsys/$prog ]; then
		echo $"${prog} is dead but subsys locked"
		return 1
	fi
	echo $"${prog} is stopped"
	return 0
}

# See how we were called.
case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  status)
	aqstatus
	RETVAL=$?
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  condrestart)
	if [ -f /var/lock/subsys/$prog ]; then
	    stop
	    start
	    RETVAL=$?
	fi
	;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

exit $RETVAL
