CREATE TABLE "ROOM" (
    "ID" NUMBER(*,0)
);
commit;

ALTER TABLE "ROOM" ADD CONSTRAINT "ROOM_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "ROOM" MODIFY ("ID" CONSTRAINT "ROOM_ID_NN" NOT NULL ENABLE);

ALTER TABLE "ROOM" ADD CONSTRAINT "ROOM_LOC_FK" FOREIGN KEY ("ID")
    REFERENCES "LOCATION" ("ID") ON DELETE CASCADE ENABLE;

commit;

