INSERT INTO "ROLE" (ID, NAME, CREATION_DATE, COMMENTS)
	VALUES (ROLE_ID_SEQ.NEXTVAL, 'maintech', SYSDATE, NULL);
INSERT INTO "ROLE" (ID, NAME, CREATION_DATE, COMMENTS)
	VALUES (ROLE_ID_SEQ.NEXTVAL, 'unixops_l2', SYSDATE, NULL);

COMMIT;
