#!/bin/bash
#
# Copyright (C) 2008,2013,2014  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Source function library
. /etc/rc.d/init.d/functions
. /etc/sysconfig/aqd
RETVAL=0

start() {
    if [[ -x $PY_BIN ]]; then
        echo -n "Starting aquilon broker: "
        if [[ $UID -ne 0 ]]; then
            RETVAL=1
            failure
        else
            su -s /bin/bash $USERNAME -c "$PY_BIN $TWISTD --logfile=$LOGFILE --pidfile=$PIDFILE aqd --config=$CONF_FILE"
            RETVAL=$?
            if [[ $RETVAL -eq 0 ]]; then
                touch $LOCKFILE
                success
            fi
        fi
        echo
        return $RETVAL
    else
        exit 5
    fi
}

stop() {
    echo -n "Stopping aquilon broker: "
    if [ $UID -ne 0 ]; then
        RETVAL=1
        failure
    else
        killproc -p $PIDFILE $PY_BIN
        RETVAL=$?
        if [[ $RETVAL -eq 0 ]]; then
            rm -f $LOCKFILE
        fi
    fi
    echo
    return $RETVAL
}

restart(){
    stop
    start
}

aqstatus(){
    status aqd >/dev/null 2>&1
}

# See how we were called.
case "$1" in
    start)
        aqstatus && exit 0
        start
        RETVAL=$?
        ;;
    stop)
        aqstatus || exit 0
        stop
        RETVAL=$?
        ;;
    restart)
        restart
        RETVAL=$?
        ;;
    force-reload)
        restart
        RETVAL=$?
        ;;
    status)
        status -p $PIDFILE aqd
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|force-reload}"
        RETVAL=2
esac

exit $RETVAL
