#!/usr/bin/env python2.6

import os
import sys

basedir = os.path.dirname(__file__)
srcdir = os.path.realpath(os.path.join(basedir, '..', 'lib', 'python2.6'))
sys.path.append(srcdir)

import aquilon.aqdb.depends
import aquilon.worker.depends
import aquilon.client.depends
# Any other packages?

# Any of the above may override the default location for ms.version...
import ms.version
ms.version.addpkg("pylint", "0.25.2")
ms.version.addpkg("logilab.astng", "0.21.1")
ms.version.addpkg("logilab.common", "0.55.0")

from pylint import lint

pylintrc = os.path.join(basedir, "pylintrc")
lint.Run(["--rcfile", pylintrc] + sys.argv[1:])
