set colsep ,     
set pagesize 0   
set trimspool on 
set headsep off  
set linesize 1000
--set numw X       

SELECT DISTINCT
    SI.NAME || ', ' || D.DEVICE_NAME || ', ' || HW.LABEL || ', ' || CLSTR.NAME || '#',
    SI.NAME, CLSTR.NAME
    -- -- SI.ID as SH_ID,
    -- SI.NAME as SHARE_NAME,
    -- -- SI.COMMENTS AS SHARE_COMMENTS, SI.CREATION_DATE AS SH_DATE,
    -- -- D.ID AS DISK_ID,
    -- D.DEVICE_NAME AS DISK_NAME,
    -- -- RES.HOLDER_ID AS HOLDER_ID,
    -- HW.LABEL AS VM_NAME,
    -- CLSTR.NAME AS CLUSTER_NAME
FROM
    SERVICE SVC, SERVICE_INSTANCE SI, DISK D,
    HARDWARE_ENTITY HW,
    VIRTUAL_MACHINE, "resource" RES, RESHOLDER, CLSTR
WHERE
    SVC.NAME = 'nas_disk_share' AND
    SI.SERVICE_ID = SVC.ID AND
    D.SERVICE_INSTANCE_ID = SI.ID AND
    D.MACHINE_ID = VIRTUAL_MACHINE.MACHINE_ID AND
    VIRTUAL_MACHINE.MACHINE_ID = HW.ID AND
    VIRTUAL_MACHINE.RESOURCE_ID = RES.ID AND
    RES.HOLDER_ID = RESHOLDER.ID AND
    RESHOLDER.CLUSTER_ID = CLSTR.ID
    order by SI.NAME, CLSTR.NAME;
EXIT;
