CREATE TABLE router_address (
	ip INTEGER CONSTRAINT "ROUTER_ADDRESS_IP_NN" NOT NULL,
	network_id INTEGER CONSTRAINT "ROUTER_ADDRESS_NETWORK_ID_NN" NOT NULL,
	location_id INTEGER,
	creation_date DATE CONSTRAINT "ROUTER_ADDRESS_CR_DATE_NN" NOT NULL,
	comments VARCHAR(255),
	CONSTRAINT "ROUTER_ADDRESS_PK" PRIMARY KEY (ip),
	CONSTRAINT "ROUTER_ADDRESS_NETWORK_FK" FOREIGN KEY (network_id) REFERENCES network (id) ON DELETE CASCADE,
	CONSTRAINT "ROUTER_ADDRESS_LOCATION_FK" FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE SET NULL
);
