DROP SEQUENCE CLSTR_SEQ;

DROP SEQUENCE METACLUSTER_SEQ;

DROP TABLE CLSTR CASCADE CONSTRAINTS;

DROP TABLE METACLUSTER CASCADE CONSTRAINTS;

DROP TABLE ESX_CLUSTER;

DROP TABLE HOST_CLUSTER_MEMBER;

DROP TABLE MACHINE_CLUSTER_MEMBER;

DROP TABLE METACLUSTER_MEMBER;

DROP TABLE CLUSTER_ALIGNED_SERVICE;

DROP TABLE CLUSTER_SERVICE_BINDING;

DROP TABLE DYNAMIC_STUB CASCADE CONSTRAINTS;

commit;
