CREATE SEQUENCE "CLSTR_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 CACHE 5 NOORDER NOCYCLE ;

CREATE TABLE "CLSTR" (
    "ID" NUMBER(*,0),
    "CLUSTER_TYPE" VARCHAR2(16),
    "NAME" VARCHAR2(64),
    "PERSONALITY_ID" NUMBER(*,0),
    "LOCATION_CONSTRAINT_ID" NUMBER(*,0),
    "MAX_HOSTS" NUMBER(*,0),
    "CREATION_DATE" DATE,
    "COMMENTS" VARCHAR2(255)
);

ALTER TABLE "CLSTR" MODIFY ("CLUSTER_TYPE" CONSTRAINT "CLSTR_CLSTR_TYP_NN" NOT NULL ENABLE);

ALTER TABLE "CLSTR" MODIFY ("CREATION_DATE" CONSTRAINT "CLSTR_CR_DATE_NN" NOT NULL ENABLE);

ALTER TABLE "CLSTR" MODIFY ("ID" CONSTRAINT "CLSTR_ID_NN" NOT NULL ENABLE);

ALTER TABLE "CLSTR" MODIFY ("NAME" CONSTRAINT "CLSTR_NAME_NN" NOT NULL ENABLE);

ALTER TABLE "CLSTR" ADD CONSTRAINT "CLUSTER_PK" PRIMARY KEY ("ID") ENABLE;

ALTER TABLE "CLSTR" MODIFY ("PERSONALITY_ID" CONSTRAINT "CLSTR_PRSNLTY_ID_NN" NOT NULL ENABLE);

ALTER TABLE "CLSTR" ADD CONSTRAINT "CLUSTER_UK" UNIQUE ("NAME", "CLUSTER_TYPE") ENABLE;

ALTER TABLE "CLSTR" ADD CONSTRAINT "CLUSTER_PRSNLTY_FK" FOREIGN KEY ("PERSONALITY_ID")
    REFERENCES "PERSONALITY" ("ID") ENABLE;

ALTER TABLE "CLSTR" ADD CONSTRAINT "CLUSTER_LOCATION_FK" FOREIGN KEY ("LOCATION_CONSTRAINT_ID")
    REFERENCES "LOCATION" ("ID") ENABLE;

------
CREATE SEQUENCE "METACLUSTER_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 CACHE 5 NOORDER NOCYCLE;

CREATE TABLE "METACLUSTER"(
    "ID" NUMBER(*,0),
    "NAME" VARCHAR2(64),
    "MAX_CLUSTERS" NUMBER(*,0),
    "CREATION_DATE" DATE,
    "COMMENTS" VARCHAR2(255)
);

ALTER TABLE "METACLUSTER" MODIFY ("CREATION_DATE" CONSTRAINT "METACLUSTER_CR_DATE_NN" NOT NULL ENABLE);

ALTER TABLE "METACLUSTER" MODIFY ("ID" CONSTRAINT "METACLUSTER_ID_NN" NOT NULL ENABLE);

ALTER TABLE "METACLUSTER" MODIFY ("MAX_CLUSTERS" CONSTRAINT "METACLUSTER_MAX_CLUSTERS_NN" NOT NULL ENABLE);

ALTER TABLE "METACLUSTER" MODIFY ("NAME" CONSTRAINT "METACLUSTER_NAME_NN" NOT NULL ENABLE);

ALTER TABLE "METACLUSTER" ADD CONSTRAINT "METACLUSTER_PK" PRIMARY KEY ("ID") ENABLE;

ALTER TABLE "METACLUSTER" ADD CONSTRAINT "METACLUSTER_UK" UNIQUE ("NAME") ENABLE;

-----
CREATE TABLE "CLUSTER_ALIGNED_SERVICE" (
    "SERVICE_ID" NUMBER(*,0),
    "CLUSTER_TYPE" VARCHAR2(16),
    "CREATION_DATE" DATE,
    "COMMENTS" VARCHAR2(255)
);

ALTER TABLE "CLUSTER_ALIGNED_SERVICE" MODIFY ("CLUSTER_TYPE" CONSTRAINT "CLSTR_ALND_SVC_CLSTR_TYP_NN" NOT NULL ENABLE);

ALTER TABLE "CLUSTER_ALIGNED_SERVICE" MODIFY ("CREATION_DATE" CONSTRAINT "CLSTR_ALND_SVC_CR_DATE_NN" NOT NULL ENABLE);

ALTER TABLE "CLUSTER_ALIGNED_SERVICE" ADD CONSTRAINT "CLSTR_ALND_SVC_PK" PRIMARY KEY ("SERVICE_ID", "CLUSTER_TYPE") ENABLE;

ALTER TABLE "CLUSTER_ALIGNED_SERVICE" MODIFY ("SERVICE_ID" CONSTRAINT "CLSTR_ALND_SVC_SVC_ID_NN" NOT NULL ENABLE);

ALTER TABLE "CLUSTER_ALIGNED_SERVICE" ADD CONSTRAINT "CLSTR_ALND_SVC_SVC_FK" FOREIGN KEY ("SERVICE_ID")
    REFERENCES "SERVICE" ("ID") ON DELETE CASCADE ENABLE;

-----
CREATE TABLE "CLUSTER_SERVICE_BINDING" (
    "CLUSTER_ID" NUMBER(*,0),
    "SERVICE_INSTANCE_ID" NUMBER(*,0),
    "CREATION_DATE" DATE,
    "COMMENTS" VARCHAR2(255)
);

ALTER TABLE "CLUSTER_SERVICE_BINDING" MODIFY ("CLUSTER_ID" CONSTRAINT "CLSTR_SVC_BNDG_CLUSTER_ID_NN" NOT NULL ENABLE);

ALTER TABLE "CLUSTER_SERVICE_BINDING" MODIFY ("CREATION_DATE" CONSTRAINT "CLSTR_SVC_BNDG_CR_DATE_NN" NOT NULL ENABLE);

ALTER TABLE "CLUSTER_SERVICE_BINDING" MODIFY ("SERVICE_INSTANCE_ID" CONSTRAINT "CLSTR_SVC_BNDG_SVC_INST_ID_NN" NOT NULL ENABLE);

ALTER TABLE "CLUSTER_SERVICE_BINDING" ADD CONSTRAINT "CLUSTER_SERVICE_BINDING_PK" PRIMARY KEY ("CLUSTER_ID", "SERVICE_INSTANCE_ID") ENABLE;

ALTER TABLE "CLUSTER_SERVICE_BINDING" ADD CONSTRAINT "CLSTR_SVC_BNDG_CLUSTER_FK" FOREIGN KEY ("CLUSTER_ID")
    REFERENCES "CLSTR" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "CLUSTER_SERVICE_BINDING" ADD CONSTRAINT "CLSTR_SVC_BNDG_SRV_INST_FK" FOREIGN KEY ("SERVICE_INSTANCE_ID")
    REFERENCES "SERVICE_INSTANCE" ("ID") ENABLE;

-----
CREATE TABLE "ESX_CLUSTER"(
    "ESX_CLUSTER_ID" NUMBER(*,0),
    "VM_TO_HOST_RATIO" NUMBER(*,0)
);

ALTER TABLE "ESX_CLUSTER" ADD CONSTRAINT "ESX_CLUSTER_FK" FOREIGN KEY ("ESX_CLUSTER_ID")
    REFERENCES "CLSTR" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "ESX_CLUSTER" ADD CONSTRAINT "ESX_CLUSTER_PK" PRIMARY KEY ("ESX_CLUSTER_ID") ENABLE;

ALTER TABLE "ESX_CLUSTER" MODIFY ("ESX_CLUSTER_ID" CONSTRAINT "ESX_CLSTR_ESX_CLSTR_ID_NN" NOT NULL ENABLE);

-----
CREATE TABLE "HOST_CLUSTER_MEMBER"(
    "CLUSTER_ID" NUMBER(*,0),
    "HOST_ID" NUMBER(*,0),
    "CREATION_DATE" DATE
);

ALTER TABLE "HOST_CLUSTER_MEMBER" MODIFY ("CLUSTER_ID" CONSTRAINT "HOST_CLSTR_MMBR_CLUSTER_ID_NN" NOT NULL ENABLE);

ALTER TABLE "HOST_CLUSTER_MEMBER" MODIFY ("CREATION_DATE" CONSTRAINT "HOST_CLSTR_MMBR_CR_DATE_NN" NOT NULL ENABLE);

ALTER TABLE "HOST_CLUSTER_MEMBER" MODIFY ("HOST_ID" CONSTRAINT "HOST_CLSTR_MMBR_HOST_ID_NN" NOT NULL ENABLE);

ALTER TABLE "HOST_CLUSTER_MEMBER" ADD CONSTRAINT "HOST_CLUSTER_MEMBER_PK" PRIMARY KEY ("CLUSTER_ID", "HOST_ID") ENABLE;

ALTER TABLE "HOST_CLUSTER_MEMBER" ADD CONSTRAINT "HOST_CLUSTER_MEMBER_HOST_UK" UNIQUE ("HOST_ID") ENABLE;

ALTER TABLE "HOST_CLUSTER_MEMBER" ADD CONSTRAINT "HST_CLSTR_MMBR_CLSTR_FK" FOREIGN KEY ("CLUSTER_ID")
    REFERENCES "CLSTR" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "HOST_CLUSTER_MEMBER" ADD CONSTRAINT "HST_CLSTR_MMBR_HST_FK" FOREIGN KEY ("HOST_ID")
    REFERENCES "HOST" ("ID") ON DELETE CASCADE ENABLE;

-----
CREATE TABLE "MACHINE_CLUSTER_MEMBER"(
    "CLUSTER_ID" NUMBER(*,0),
    "MACHINE_ID" NUMBER(*,0),
    "CREATION_DATE" DATE
);

ALTER TABLE "MACHINE_CLUSTER_MEMBER" ADD CONSTRAINT "MACHINE_CLUSTER_MEMBER_PK" PRIMARY KEY ("CLUSTER_ID", "MACHINE_ID") ENABLE;

ALTER TABLE "MACHINE_CLUSTER_MEMBER" MODIFY ("CLUSTER_ID" CONSTRAINT "MCHN_CLSTR_MMBR_CLUSTER_ID_NN" NOT NULL ENABLE);

ALTER TABLE "MACHINE_CLUSTER_MEMBER" MODIFY ("CREATION_DATE" CONSTRAINT "MCHN_CLSTR_MMBR_CR_DATE_NN" NOT NULL ENABLE);

ALTER TABLE "MACHINE_CLUSTER_MEMBER" MODIFY ("MACHINE_ID" CONSTRAINT "MCHN_CLSTR_MMBR_MACHINE_ID_NN" NOT NULL ENABLE);

ALTER TABLE "MACHINE_CLUSTER_MEMBER" ADD CONSTRAINT "MACHINE_CLUSTER_MEMBER_UK" UNIQUE ("MACHINE_ID") ENABLE;

ALTER TABLE "MACHINE_CLUSTER_MEMBER" ADD CONSTRAINT "MCHN_CLSTR_MMBR_CLSTR_FK" FOREIGN KEY ("CLUSTER_ID")
    REFERENCES "CLSTR" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "MACHINE_CLUSTER_MEMBER" ADD CONSTRAINT "MCHN_CLSTR_MMBR_MCHN_FK" FOREIGN KEY ("MACHINE_ID")
    REFERENCES "MACHINE" ("MACHINE_ID") ON DELETE CASCADE ENABLE;

-----
CREATE TABLE "METACLUSTER_MEMBER" (
    "METACLUSTER_ID" NUMBER(*,0),
    "CLUSTER_ID" NUMBER(*,0),
    "CREATION_DATE" DATE
);

ALTER TABLE "METACLUSTER_MEMBER" ADD CONSTRAINT "METACLUSTER_MEMBER_PK" PRIMARY KEY ("METACLUSTER_ID", "CLUSTER_ID") ENABLE;

ALTER TABLE "METACLUSTER_MEMBER" ADD CONSTRAINT "METACLUSTER_MEMBER_UK" UNIQUE ("CLUSTER_ID") ENABLE;

ALTER TABLE "METACLUSTER_MEMBER" MODIFY ("CLUSTER_ID" CONSTRAINT "MTACLSTR_MBR_CLUSTER_ID_NN" NOT NULL ENABLE);

ALTER TABLE "METACLUSTER_MEMBER" MODIFY ("CREATION_DATE" CONSTRAINT "MTACLSTR_MBR_CR_DATE_NN" NOT NULL ENABLE);

ALTER TABLE "METACLUSTER_MEMBER" MODIFY ("METACLUSTER_ID" CONSTRAINT "MTACLSTR_MBR_MTACLSTR_ID_NN" NOT NULL ENABLE);

ALTER TABLE "METACLUSTER_MEMBER" ADD CONSTRAINT "METACLUSTER_MEMBER_CLSTR_FK" FOREIGN KEY ("CLUSTER_ID")
    REFERENCES "CLSTR" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "METACLUSTER_MEMBER" ADD CONSTRAINT "METACLUSTER_MEMBER_META_FK" FOREIGN KEY ("METACLUSTER_ID")
    REFERENCES "METACLUSTER" ("ID") ON DELETE CASCADE ENABLE;

commit;
