ALTER TABLE host RENAME COLUMN machine_id TO hardware_entity_id;
ALTER TABLE host RENAME CONSTRAINT HOST_MACHINE_ID_NN TO HOST_HW_ENT_ID_NN;
ALTER TABLE host DROP CONSTRAINT "HOST_MACHINE_FK";
ALTER TABLE host ADD CONSTRAINT "HOST_HWENT_FK" FOREIGN KEY (hardware_entity_id) REFERENCES hardware_entity (id);

QUIT;
