#! /bin/sh
#
# Copyright (C) 2011,2013  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DATADIR=$(dirname "$0")/qip-subnetdata.d

OUTPUTDIR="$PWD"
FORMAT=

while [ -n "$1" ]; do
	case "$1" in
		--datarootdir)
			OUTPUTDIR="$2"
			shift
			;;
		--noaudit)
			;;
		--format)
			FORMAT="$2"
			shift
			;;
		*)
			echo "Unknown option $1" 1>&2
			exit 1
	esac
	shift
done

if [ "$FORMAT" != "txt" ]; then
	echo "Unsupported format $FORMAT" 1>&2
	exit 1
fi

cp "$DATADIR"/subnetdata.txt "$OUTPUTDIR"/subnetdata.txt
exit 0
