#!/bin/bash
read -t 2 input
echo $input|grep 'size: 15' 2>&1 >/dev/null
if [ $? -eq 0 ]; then
    cat <<EOF
---
_error:
  from: borkstation
  in:
    rack: ut11
    size: 15
  pk: test
  verb: create
  when: 2011-03-09 15:38:34 GMT
  where: ./nasassign
  who: arenberg
  why:
    default:
    - data@size schema@attr_hashes/3/keys/size/attr_hashes/0/one_of data must be one
      of [30, 40, 50]
EOF
exit 0;
fi;
echo $input|grep '_id: sde_evm10' 2>&1 >/dev/null
if [ $? -eq 0 ]; then
    cat <<EOF
---
_error:
  from: borkstation
  in:
    _id: sde_evm10
    days_to_expire: -1
    description: nasassign
    devdb: 1
    eon: 1
    owner: arenberg
    rack: ut11
    resourcegroup_name: sde_evm10
    size: 30
  pk: sde_evm10
  verb: create
  when: 2011-03-09 22:01:35 GMT
  where: /ms/dist/virtual/PROJ/resourcepool-laf/0.2/bin/nasassign
  who: arenberg
  why: Requested number of nas slots are not available. Please inform administrator.
EOF
exit 0;
fi;
if [ "$1" == 'create' ]; then
    cat <<EOF
        _id: diskname_machinename
        days_to_expire: -1
        description: nasassign
        devdb: 1
        eon: 1
        owner: $USER
        rack: dd1
        resourcegroup_name: diskname_machinename
        sharename: utecl13_share
        size: 30
EOF
fi;
