#!/ms/dist/python/PROJ/core/2.5.0/bin/python
# ex: set expandtab softtabstop=4 shiftwidth=4: -*- cpy-indent-level: 4; indent-tabs-mode: nil -*-
# Copyright (C) 2008 Morgan Stanley
#
# This module is part of Aquilon
"""Fake the CheckNet command"""


from __future__ import with_statement

import sys
import os


def determine_output(args):
    """ This may need to be more complicated some day.  For now, just return
        a known past request."""
    return os.path.realpath(os.path.join(
        os.path.dirname(__file__), "CheckNet.d", 
        "CheckNet_-ho_np06bals03_camtable_-nobanner_-table_1_-noprompt.out"))

def fake_checknet(args):
    with open(determine_output(args)) as f:
        for line in f:
            sys.stdout.write(line)


if __name__=='__main__':
    fake_checknet(sys.argv)

