#! /bin/sh
#
# Copyright (C) 2010,2011,2013  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DATADIR=$(dirname "$0")/dsdb.d

if [ -z "$AQTEST_DSDB_COVERAGE_DIR" ]; then
	exit 0
fi

echo "$*" >> "${AQTEST_DSDB_COVERAGE_DIR}/issued_dsdb_cmds"

if grep -q "^$*\$" "${AQTEST_DSDB_COVERAGE_DIR}/expected_dsdb_cmds" 2>/dev/null; then
	# Is it a command that should generate some output?
	ARGSTR=`echo $* | sed -e 's![ /]!_!g'`
	if [ -e "${DATADIR}/${ARGSTR}" ]; then
		cat "${DATADIR}/${ARGSTR}"
	fi
	exit 0
fi

if grep -q "^$*\$" "${AQTEST_DSDB_COVERAGE_DIR}/fail_expected_dsdb_cmds" 2>/dev/null; then
	# Yes, it's stdout, not stderr
	if [ -s "${AQTEST_DSDB_COVERAGE_DIR}/fail_expected_dsdb_error" ]; then
	   cat "${AQTEST_DSDB_COVERAGE_DIR}/fail_expected_dsdb_error"
	   exit 255
	fi
	echo "Your query returned no data!"
	exit 255
fi

echo "Error: fake_dsdb was called with unexpected parameters" 1>&2

# Some extra info to make debugging easier...
if [ -s "${AQTEST_DSDB_COVERAGE_DIR}/expected_dsdb_cmds" ]; then
	echo "Commands that were expected to be called successfully: " 1>&2
	echo "---< CUT >---" 1>&2
	cat "${AQTEST_DSDB_COVERAGE_DIR}/expected_dsdb_cmds" 1>&2
	echo "---< CUT >---" 1>&2
fi
if [ -s "${AQTEST_DSDB_COVERAGE_DIR}/fail_expected_dsdb_cmds" ]; then
	echo "Commands that were expected to be called and fail:" 1>&2
	echo "---< CUT >---" 1>&2
	cat "${AQTEST_DSDB_COVERAGE_DIR}/fail_expected_dsdb_cmds" 1>&2
	echo "---< CUT >---" 1>&2
fi

exit 1
