#!/bin/bash
#
# Copyright (C) 2017  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "$2" | egrep -q "^[a-z]+://[0-9]+$"
if [ $? -eq 0 ]; then
  nb="$(echo $2 | cut -d/ -f3)"
  if [ "$nb" == "003427" ] && [ "$6" != "cards" ]; then
    echo "Location URI not valid: Building name and URI do not match"
    exit 1
  elif [ "$nb" == "005555" ]; then
    echo "Warning: 'IT_CODE' in '(.*)' is empty for URI 'assetinventory://005555'! Proceeding without validation."
    exit 0
  fi
  exit 0
else
  echo "URI '$2' is not formatted correctly. It must be of the form 'string://012345' where the number contains 6 digits and is zero-padded."
  exit 1
fi
