#! /bin/sh
#
# Copyright (C) 2018  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

error () {
    echo "$@" 1>&2
    exit 1
}

while [ -n "$1" ]; do
	case "$1" in
		-s)
			SOURCE="$2"
			shift
			;;
		-t)
			TARGET="$2"
			shift
			;;
		-c)
			COMMIT="$2"
			shift
			;;
		-a)
			ASSIGN="$2"
			shift
			;;
		*)
			echo "Unknown option $1" 1>&2
			exit 1
	esac
	shift
done

test -n "$SOURCE" || error "Missing source branch name"

test -n "$TARGET" || error "Missing target domain name"

test -n "$COMMIT" || error "Missing commit id"

echo '{"URL": "TEST_GERRIT_PR_URL"}'
exit 0