#!/ms/dist/python/PROJ/core/2.5.2-1/bin/python
# ex: set expandtab softtabstop=4 shiftwidth=4: -*- cpy-indent-level: 4; indent-tabs-mode: nil -*-
# Copyright (C) 2008 Morgan Stanley
#
# This module is part of Aquilon
"""Fake the vlan command"""


from __future__ import with_statement

import sys
import os


def determine_output(args):
    """ Figure out which file has the necessary contents for the request."""
    ip = None
    for i in range(len(args)):
        if args[i].startswith("-ip"):
            if i == len(args):
                print >>sys.stderr, "Missing argument for %s" % args[i]
                sys.exit(1)
            ip = args[i+1]
            break
    if not ip:
        print >>sys.stderr, "Missing -ip argument" % args[i]
        sys.exit(1)
    fakedir = os.path.realpath(os.path.join(os.path.dirname(__file__),
                                            "vlan2net.d"))
    return os.path.join(fakedir, "vlan2net_-ip_%s.out" % ip)

def fake_vlan2net(args):
    with open(determine_output(args)) as f:
        for line in f:
            sys.stdout.write(line)


if __name__=='__main__':
    fake_vlan2net(sys.argv)
