#!/usr/bin/env python2.6
# -*- cpy-indent-level: 4; indent-tabs-mode: nil -*-
# ex: set expandtab softtabstop=4 shiftwidth=4:
#
# Copyright (C) 2010,2013  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Fake the vlan command"""


import sys
import os


def determine_output(args):
    """ Figure out which file has the necessary contents for the request."""
    ip = None
    for i in range(len(args)):
        if args[i].startswith("-ip"):
            if i == len(args):
                print >>sys.stderr, "Missing argument for %s" % args[i]
                sys.exit(1)
            ip = args[i+1]
            break
    if not ip:
        print >>sys.stderr, "Missing -ip argument" % args[i]
        sys.exit(1)
    fakedir = os.path.realpath(os.path.join(os.path.dirname(__file__),
                                            "vlan2net.d"))
    return os.path.join(fakedir, "vlan2net_-ip_%s.out" % ip)

def fake_vlan2net(args):
    with open(determine_output(args)) as f:
        for line in f:
            sys.stdout.write(line)


if __name__=='__main__':
    fake_vlan2net(sys.argv)
