#! /bin/sh
#
# Copyright (C) 2011,2013  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

error () {
    echo "$@" 1>&2
    exit 1
}

# Skip anything that looks like an ssh option
while true; do
	case "$1" in
		-[bcDeFiLlmopRS]) shift 2;;
		-[1246AaCfgkMNnqsTtVvXxY]) shift;;
		-*) error "I don't know anything about option $1";;
		*) break;;
	esac
done

# Skip the remote host name
test -n "$1" || error "Missing host name"
shift

# Check if there's anything to run
test -n "$1" || error "Interactive use is not supported, please specify a command"

# Execute the command locally
exec "$@"
