-- host grn map
ALTER TABLE HOST_GRN_MAP ADD TARGET VARCHAR(32);

UPDATE HOST_GRN_MAP SET TARGET = 'esp';
ALTER TABLE HOST_GRN_MAP MODIFY (TARGET VARCHAR(32) CONSTRAINT "HOST_GRN_MAP_TARGET_NN" NOT NULL);

ALTER TABLE HOST_GRN_MAP DROP CONSTRAINT host_grn_map_pk;
DROP INDEX host_grn_map_pk;
ALTER TABLE HOST_GRN_MAP ADD CONSTRAINT host_grn_map_pk PRIMARY KEY ("HOST_ID", "EON_ID", "TARGET");

-- personality grn map
ALTER TABLE PERSONALITY_GRN_MAP ADD TARGET VARCHAR(32);

UPDATE PERSONALITY_GRN_MAP SET TARGET = 'esp';
ALTER TABLE PERSONALITY_GRN_MAP MODIFY (TARGET VARCHAR(32) CONSTRAINT "PERS_GRN_MAP_TARGET_NN" NOT NULL);

ALTER TABLE PERSONALITY_GRN_MAP DROP CONSTRAINT personality_grn_map_pk;
DROP INDEX personality_grn_map_pk;
ALTER TABLE PERSONALITY_GRN_MAP ADD CONSTRAINT personality_grn_map_pk PRIMARY KEY ("PERSONALITY_ID", "EON_ID", "TARGET");

COMMIT;
QUIT;

