CREATE TABLE grn (
	eon_id INTEGER CONSTRAINT "GRN_EON_ID_NN" NOT NULL,
	grn VARCHAR2(255 CHAR) CONSTRAINT "GRN_GRN_NN" NOT NULL,
	disabled INTEGER CONSTRAINT "GRN_DISABLED_NN" NOT NULL,
	creation_date DATE CONSTRAINT "GRN_CR_DATE_NN" NOT NULL,
	CONSTRAINT "GRN_PK" PRIMARY KEY (eon_id),
	CONSTRAINT "GRN_DISABLED_CK" CHECK (disabled IN (0, 1))
);

CREATE UNIQUE INDEX "GRN_GRN_UK" ON grn(grn);

QUIT;
