CREATE INDEX a_record_network_ip_idx ON a_record (network_id, ip);
CREATE INDEX a_record_reverse_ptr_idx ON a_record (reverse_ptr_id);
CREATE INDEX addr_assign_network_ip_idx ON address_assignment (network_id, ip);
CREATE INDEX addr_assign_service_addr_idx ON address_assignment (service_address_id);
CREATE INDEX addr_assign_dns_env_idx ON address_assignment (dns_environment_id);
CREATE INDEX alias_target_idx ON alias (target_id);
CREATE INDEX build_item_si_idx ON build_item (service_instance_id);
CREATE INDEX domain_tracked_branch_idx ON domain (tracked_branch_id);
CREATE INDEX cluster_branch_idx ON clstr (branch_id);
CREATE INDEX cluster_prsnlty_idx ON clstr (personality_id);
CREATE INDEX cluster_location_idx ON clstr (location_constraint_id);
CREATE INDEX clstr_allow_per_prsnlty_idx ON clstr_allow_per (personality_id);
CREATE INDEX clstr_svc_bndg_si_idx ON cluster_service_binding (service_instance_id);
CREATE INDEX disk_share_idx ON disk (share_id);
CREATE INDEX dns_record_fqdn_idx ON dns_record (fqdn_id);
CREATE INDEX esx_cluster_switch_idx ON esx_cluster (switch_id);
CREATE INDEX feature_link_model_idx ON feature_link (model_id);
CREATE INDEX feature_link_archetype_idx ON feature_link (archetype_id);
CREATE INDEX feature_link_personality_idx ON feature_link (personality_id);
CREATE INDEX fqdn_dns_env_idx ON fqdn (dns_environment_id);
CREATE INDEX hw_ent_model_idx ON hardware_entity (model_id);
CREATE INDEX host_branch_idx ON host (branch_id);
CREATE INDEX iface_model_idx ON interface (model_id);
CREATE INDEX iface_master_idx ON interface (master_id);
CREATE INDEX location_link_parent_idx ON location_link (parent_id);
CREATE INDEX observed_vlan_network_idx ON observed_vlan (network_id);
CREATE INDEX observed_vlan_vlan_idx ON observed_vlan (vlan_id);
CREATE INDEX parameter_holder_idx ON parameter (holder_id);
CREATE INDEX param_definition_holder_idx ON param_definition (holder_id);
CREATE INDEX prsnlty_svc_map_location_idx ON personality_service_map (location_id);
CREATE INDEX prsnlty_svc_map_si_idx ON personality_service_map (service_instance_id);
CREATE INDEX prsnlty_svc_map_network_idx ON personality_service_map (network_id);
CREATE INDEX resource_holder_idx ON "resource" (holder_id);
CREATE INDEX router_address_dns_env_idx ON router_address (dns_environment_id);
CREATE INDEX router_address_location_idx ON router_address (location_id);
CREATE INDEX svc_map_location_idx ON service_map (location_id);
CREATE INDEX svc_map_network_idx ON service_map (network_id);
CREATE INDEX sis_host_idx ON service_instance_server (host_id);
CREATE INDEX srv_addr_dns_record_idx ON service_address (dns_record_id);
CREATE INDEX srv_record_target_idx ON srv_record (target_id);
CREATE INDEX static_route_gw_network_ip_idx ON static_route (network_id, gateway_ip);

QUIT;
