CREATE TABLE alias (
	dns_record_id INTEGER CONSTRAINT "ALIAS_DNS_RECORD_ID_NN" NOT NULL,
	target_id INTEGER CONSTRAINT "ALIAS_TARGET_ID_NN" NOT NULL,
	CONSTRAINT "ALIAS_PK" PRIMARY KEY (dns_record_id),
	CONSTRAINT "ALIAS_DNS_RECORD_FK" FOREIGN KEY (dns_record_id) REFERENCES dns_record (id) ON DELETE CASCADE,
	CONSTRAINT "ALIAS_TARGET_FK" FOREIGN KEY (target_id) REFERENCES fqdn (id) ON DELETE CASCADE
);

ALTER TABLE dns_domain ADD restricted INTEGER;
ALTER TABLE dns_domain ADD CONSTRAINT "DNS_DOMAIN_RESTRICTED_CK" CHECK (restricted IN (0, 1));
UPDATE dns_domain SET restricted = 0;
ALTER TABLE dns_domain MODIFY (restricted INTEGER CONSTRAINT "DNS_DOMAIN_RESTRICTED_NN" NOT NULL);
