CREATE TABLE alias (
	dns_record_id INTEGER CONSTRAINT "ALIAS_DNS_RECORD_ID_NN" NOT NULL,
	target_id INTEGER CONSTRAINT "ALIAS_TARGET_ID_NN" NOT NULL,
	CONSTRAINT "ALIAS_PK" PRIMARY KEY (dns_record_id),
	CONSTRAINT "ALIAS_DNS_RECORD_FK" FOREIGN KEY (dns_record_id) REFERENCES dns_record (id) ON DELETE CASCADE,
	CONSTRAINT "ALIAS_TARGET_FK" FOREIGN KEY (target_id) REFERENCES fqdn (id) ON DELETE CASCADE
);
