
/* DELETE FROM BUILD_ITEM WHERE CFG_PATH_ID IN
    (SELECT id FROM CFG_PATH WHERE TLD_ID = (SELECT ID FROM TLD WHERE TYPE ='os'));
COMMIT;
*/

ALTER TABLE BUILD_ITEM DROP COLUMN CFG_PATH_ID;
ALTER TABLE BUILD_ITEM ADD CONSTRAINT "BUILD_ITEM_UK" UNIQUE ("HOST_ID", "SERVICE_INSTANCE_ID");
ALTER TABLE BUILD_ITEM DROP CONSTRAINT HOST_POSITION_UK;
ALTER TABLE BUILD_ITEM DROP COLUMN "POSITION";

DROP TABLE CFG_PATH CASCADE CONSTRAINTS;
DROP TABLE TLD CASCADE CONSTRAINTS;

ALTER TABLE SERVICE DROP COLUMN "CFG_PATH_ID";
ALTER TABLE SERVICE_INSTANCE DROP COLUMN "CFG_PATH_ID";

ALTER TABLE "HOST" ADD CONSTRAINT "HOST_OS_FK" FOREIGN KEY ("OPERATING_SYSTEM_ID")
    REFERENCES "OPERATING_SYSTEM" ("ID") ENABLE;

ALTER TABLE "HOST" MODIFY ("OPERATING_SYSTEM_ID" NOT NULL);
ALTER TABLE "HOST" ADD CONSTRAINT "HOST_OS_ID_NN" CHECK ("OPERATING_SYSTEM_ID" IS NOT NULL) ENABLE;
ALTER TABLE "HOST" MODIFY ("PERSONALITY_ID" NOT NULL);
ALTER TABLE "HOST" ADD CONSTRAINT "HOST_PERSONALITY_ID_NN" CHECK ("PERSONALITY_ID" IS NOT NULL) ENABLE;

COMMIT;
