ALTER TABLE clstr DROP CONSTRAINT "CLSTR_DOWN_HOSTS_NN";
ALTER TABLE clstr MODIFY (down_hosts_percent INTEGER CONSTRAINT "CLSTR_DOWN_HOSTS_PERCENT_NN" NOT NULL);
ALTER TABLE clstr MODIFY (down_hosts_threshold INTEGER CONSTRAINT "CLSTR_DOWN_HOSTS_THR_NN" NOT NULL);
ALTER TABLE clstr MODIFY (down_maint_percent INTEGER CONSTRAINT "CLSTR_DOWN_MAINT_PERCENT_NN" NOT NULL);

ALTER TABLE metacluster DROP CONSTRAINT "METACLUSTER_HA_CK";
ALTER TABLE metacluster ADD CONSTRAINT "METACLUSTER_HA_CK" CHECK (high_availability IN (0, 1));

UPDATE personality SET cluster_required = 0 WHERE cluster_required IS NULL;
ALTER TABLE personality MODIFY (cluster_required INTEGER CONSTRAINT "PERSONALITY_CLSTR_REQ_NN" NOT NULL);
ALTER TABLE personality DROP CONSTRAINT "PERSONALITY_CLSTR_REQ_CK";
ALTER TABLE personality ADD CONSTRAINT "PERSONALITY_CLSTR_REQ_CK" CHECK (cluster_required IN (0, 1));

QUIT;
