CREATE INDEX SERVICE_ADDRESS_DNS_RECORD_IDX ON SERVICE_ADDRESS (DNS_RECORD_ID);
ALTER TABLE SERVICE_ADDRESS DROP CONSTRAINT "SERVICE_ADDRESS_DNS_RECORD_UK";
DROP INDEX "SERVICE_ADDRESS_DNS_RECORD_UK";
QUIT;
