ALTER TABLE "SERVICE_INSTANCE" ADD "MANAGER" VARCHAR2(32 CHAR);
UPDATE "SERVICE_INSTANCE" SET "MANAGER" = 'aqd';
ALTER TABLE "SERVICE_INSTANCE" ADD CONSTRAINT "SVC_INST_MANAGER_NN" CHECK ("MANAGER" IS NOT NULL) ENABLE;
COMMIT;
QUIT;
