ALTER TABLE "SERVICE_INSTANCE" ADD "MANAGER" VARCHAR2(32 CHAR);
UPDATE "SERVICE_INSTANCE" SET "MANAGER" = 'aqd';
ALTER TABLE "SERVICE_INSTANCE" MODIFY ("MANAGER" CONSTRAINT "SVC_INST_MANAGER_NN" NOT NULL ENABLE);
COMMIT;
QUIT;
