CREATE SEQUENCE static_route_id_seq;
CREATE TABLE static_route (
	id INTEGER CONSTRAINT "STATIC_ROUTE_ID_NN" NOT NULL,
	gateway_ip INTEGER CONSTRAINT "STATIC_ROUTE_GATEWAY_IP_NN" NOT NULL,
	network_id INTEGER CONSTRAINT "STATIC_ROUTE_NETWORK_ID_NN" NOT NULL,
	dest_ip INTEGER CONSTRAINT "STATIC_ROUTE_DEST_IP" NOT NULL,
	dest_cidr INTEGER CONSTRAINT "STATIC_ROUTE_DEST_CIDR" NOT NULL,
	creation_date DATE CONSTRAINT "STATIC_ROUTE_CR_DATE_NN" NOT NULL,
	comments VARCHAR2(255 CHAR),
	CONSTRAINT "STATIC_ROUTE_PK" PRIMARY KEY (id),
	CONSTRAINT "STATIC_ROUTE_NETWORK_FK" FOREIGN KEY (network_id) REFERENCES network (id)
);

QUIT;
