ALTER TABLE STATIC_ROUTE ADD ("PERSONALITY_ID" INTEGER);

ALTER TABLE STATIC_ROUTE
	ADD CONSTRAINT "STATIC_ROUTE_PRSNLTY_FK"
	FOREIGN KEY ("PERSONALITY_ID")
	REFERENCES "PERSONALITY" ("ID")
	ON DELETE CASCADE ENABLE
;
