#!/bin/bash
#
# Copyright (C) 2018  Contributor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if git diff --cached --quiet ; then
	# This commit just updated the last commit message at most,
	# we thus do not have to do anything about it, we can just
	# exit silently
	exit 0
fi

# Check the code style to insure that it is compliant with
# the flake8 rules
tests/codestyle.py --staged
EXIT=$?
if [ "$EXIT" != "0" ]; then
	echo -e "\e[1m\e[41mCode style errors: commit aborted\e[0m" >&2
	exit $EXIT
fi

# If we reach here, everything was fine
exit 0
