ANALYZE TABLE ARCHETYPE COMPUTE STATISTICS;
ANALYZE TABLE BUILDING COMPUTE STATISTICS;
ANALYZE TABLE BUILD_ITEM COMPUTE STATISTICS;
ANALYZE TABLE CFG_PATH COMPUTE STATISTICS;
ANALYZE TABLE DOMAIN COMPUTE STATISTICS;
ANALYZE TABLE HARDWARE_ENTITY COMPUTE STATISTICS;
ANALYZE TABLE HOST COMPUTE STATISTICS;
ANALYZE TABLE LOCATION COMPUTE STATISTICS;
ANALYZE TABLE MACHINE COMPUTE STATISTICS;
ANALYZE TABLE SERVICE COMPUTE STATISTICS;
ANALYZE TABLE SERVICE_INSTANCE COMPUTE STATISTICS;
ANALYZE TABLE SERVICE_MAP COMPUTE STATISTICS;
ANALYZE TABLE SYSTEM COMPUTE STATISTICS;
ANALYZE TABLE TLD COMPUTE STATISTICS;
ANALYZE TABLE PERSONALITY COMPUTE STATISTICS;

begin 
  DBMS_STATS.GATHER_SCHEMA_STATS (
    ownname => 'cdb',
    --options=>'GATHER EMPTY',
    --method_opt=>'for all columns size repeat',
    cascade => TRUE,
    estimate_percent => 100);
end;
commit;
exit;
