ALTER TABLE ESX_CLUSTER ADD (DOWN_HOSTS_THRESHOLD NUMBER(*, 0));

UPDATE ESX_CLUSTER SET DOWN_HOSTS_THRESHOLD=0;
UPDATE ESX_CLUSTER SET DOWN_HOSTS_THRESHOLD=2 WHERE EXISTS (
	SELECT 1 FROM CLSTR WHERE ID = ESX_CLUSTER_ID AND MAX_HOSTS = 8);
UPDATE ESX_CLUSTER SET DOWN_HOSTS_THRESHOLD=4 WHERE EXISTS (
	SELECT 1 FROM CLSTR WHERE ID = ESX_CLUSTER_ID AND MAX_HOSTS = 12);
UPDATE ESX_CLUSTER SET DOWN_HOSTS_THRESHOLD=6 WHERE EXISTS (
	SELECT 1 FROM CLSTR WHERE ID = ESX_CLUSTER_ID AND MAX_HOSTS = 16);
commit;

ALTER TABLE ESX_CLUSTER
ADD CONSTRAINT ESX_CLSTR_THRSH_NN CHECK
(DOWN_HOSTS_THRESHOLD IS NOT NULL)
ENABLE;
commit;

UPDATE ESX_CLUSTER SET VM_COUNT = 1, HOST_COUNT = 1
	WHERE VM_COUNT = 8 AND HOST_COUNT = 12;
UPDATE ESX_CLUSTER SET VM_COUNT = 15, HOST_COUNT = 1
	WHERE VM_COUNT = 10 AND HOST_COUNT = 1;
commit;
